optimizer_name_G: Adam
optimizer_config_G:
  lr: 2.75e-05
  betas: &id001 !!python/tuple [0.5, 0.999]
lr_scheduler_name_G: null
lr_scheduler_config_G: {}
optimizer_name_D: Adam
optimizer_config_D:
  lr: 2.25e-05
  betas: *id001
lr_scheduler_name_D: null
lr_scheduler_config_D: {}
n_iters: 20000
batch_size: 256
